/** Generado por scripts/generate-password-bank.mjs. No editar a mano. */
export const PASSWORD_WORDS = [
  "Maná",
  "Arca de Noé",
  "Arca del pacto",
  "Zarza ardiente",
  "Mar Rojo",
  "Diez mandamientos",
  "Tablas de piedra",
  "Monte Sinaí",
  "Jardín del Edén",
  "Árbol de la vida",
  "Fruto prohibido",
  "Torre de Babel",
  "Escalera de Jacob",
  "Túnica de colores",
  "Vellón de Gedeón",
  "Honda de David",
  "Quijada de Sansón",
  "Cabellera de Sansón",
  "Foso de los leones",
  "Horno de fuego",
  "Muros de Jericó",
  "Trompetas",
  "Vara de Aarón",
  "Serpiente de bronce",
  "Columna de fuego",
  "Nube de día",
  "Tienda de reunión",
  "Candelabro",
  "Pan de la proposición",
  "Incienso",
  "Altar",
  "Sacerdote",
  "Levita",
  "Profeta",
  "Sacrificio",
  "Cordero pascual",
  "Sangre en la puerta",
  "Plagas de Egipto",
  "Langostas",
  "Ranas",
  "Granizo",
  "Faraón",
  "Éxodo",
  "Tierra prometida",
  "Leche y miel",
  "Doce tribus",
  "Doce espías",
  "Racimo de uvas",
  "Jordán",
  "Bautismo",
  "Paloma",
  "Espíritu Santo",
  "Ángel",
  "Querubín",
  "Arcángel Miguel",
  "Gigante Goliat",
  "Rey David",
  "Salmo",
  "Arpa",
  "Rey Salomón",
  "Templo",
  "Sabiduría",
  "Reina de Saba",
  "Proverbio",
  "Job",
  "Paciencia",
  "Elías",
  "Carro de fuego",
  "Cuervos",
  "Eliseo",
  "Manto",
  "Jonás",
  "Gran pez",
  "Nínive",
  "Ester",
  "Banquete",
  "Nehemías",
  "Murallas",
  "Daniel",
  "Sueño del rey",
  "Escritura en la pared",
  "Belén",
  "Pesebre",
  "Estrella de oriente",
  "Reyes magos",
  "Oro, incienso y mirra",
  "Pastores",
  "Ángel Gabriel",
  "María",
  "José el carpintero",
  "Juan el Bautista",
  "Desierto",
  "Tentación",
  "Doce apóstoles",
  "Pescadores de hombres",
  "Redes",
  "Barca",
  "Tempestad calmada",
  "Caminar sobre el agua",
  "Agua en vino",
  "Bodas de Caná",
  "Cinco panes y dos peces",
  "Multiplicación",
  "Ciego de nacimiento",
  "Leproso sanado",
  "Paralítico",
  "Camilla",
  "Lázaro",
  "Resurrección",
  "Hijo pródigo",
  "Oveja perdida",
  "Moneda perdida",
  "Buen samaritano",
  "Sembrador",
  "Semilla de mostaza",
  "Talentos",
  "Diez vírgenes",
  "Lámparas de aceite",
  "Buen pastor",
  "Puerta",
  "Vid y pámpanos",
  "Sal de la tierra",
  "Luz del mundo",
  "Bienaventuranzas",
  "Padre nuestro",
  "Perdón",
  "Amor al prójimo",
  "Fe",
  "Esperanza",
  "Zaqueo",
  "Sicómoro",
  "Mujer samaritana",
  "Pozo de Jacob",
  "Marta y María",
  "Perfume de nardo",
  "Última cena",
  "Pan y vino",
  "Lavatorio de pies",
  "Getsemaní",
  "Beso de Judas",
  "Treinta monedas",
  "Gallo de Pedro",
  "Corona de espinas",
  "Cruz",
  "Calvario",
  "Clavos",
  "Velo rasgado",
  "Tumba vacía",
  "Piedra rodada",
  "Camino a Emaús",
  "Tomás el incrédulo",
  "Ascensión",
  "Pentecostés",
  "Lenguas de fuego",
  "Iglesia primitiva",
  "Camino a Damasco",
  "Pablo",
  "Naufragio",
  "Cárcel",
  "Cadenas rotas",
  "Cartas",
  "Armadura de Dios",
  "Escudo de la fe",
  "Espada del Espíritu",
  "Cielo nuevo",
  "Tierra nueva",
  "Apocalipsis",
  "Siete sellos",
  "Alfa y Omega",
  "Nueva Jerusalén",
  "Calles de oro"
] as const;
